spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kutuphane_otomasyon_sistemi?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 12922345
    initialize: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


  mail:
    host: smtp.gmail.com
    port: 587
    username: example@gmail.com
    password: 123456
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          port: 587
          host: smtp.gmail.com
          auth: true
          starttls:
            enable: true
otomasyon_sistemi:
  app:
    jwtSecret : bezKoderSecretKey
    jwtExpirationMs : 86400000